import Foundation

/// Pasteboard types that mean "do not record this".
///
/// These are the nspasteboard.org convention, not AppKit constants — grepping
/// `NSPasteboard.h` in the macOS 26 SDK for `Concealed|Transient|AutoGenerated`
/// returns nothing. All three `org.nspasteboard.*` strings do ship inside
/// macOS 26.6.2, and password managers set them, so honouring them is the
/// difference between a clipboard manager and a keylogger.
enum PrivacyMarkers {
    /// Content that must never be stored at all.
    static let rejected: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    /// Content that may be stored but must be masked in the UI.
    static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.agilebits.onepassword",
    ]

    /// True when any representation marks the content as not-for-recording.
    static func isRejected(types: some Sequence<String>) -> Bool {
        types.contains { rejected.contains($0) }
    }

    /// True when any representation marks the content as sensitive.
    static func isConcealed(types: some Sequence<String>) -> Bool {
        types.contains { concealed.contains($0) }
    }
}
