import Foundation
import Testing

@testable import SkrepkaCore

@Suite("Capture rules")
struct CaptureRulesTests {
    private func snapshot(
        _ representations: [String: Data],
        declaring extraTypes: [String] = [],
        files: [URL] = [],
        source: String? = nil
    ) -> PasteboardSnapshot {
        PasteboardSnapshot(
            representations: representations,
            declaredTypes: Array(representations.keys) + extraTypes,
            fileURLs: files,
            sourceBundleID: source
        )
    }

    /// `count` file URLs that need not exist — nothing the capture rules do
    /// touches the disk.
    private func selectionOf(_ count: Int) -> [URL] {
        (0..<count).compactMap { URL(string: "file:///Users/me/file-\($0).txt") }
    }

    private func text(_ string: String) -> [String: Data] {
        [PasteboardType.string: Data(string.utf8)]
    }

    @Test("Plain text is captured as .text")
    func capturesPlainText() throws {
        let decision = CaptureRules().decide(snapshot(text("hello")))
        let item = try #require(decision.item)
        #expect(item.kind == .text)
        #expect(item.text == "hello")
        #expect(!item.isConcealed)
    }

    @Test("Transient markers are rejected before any data is read")
    func rejectsTransientMarker() {
        let decision = CaptureRules().decide(
            snapshot(text("secret"), declaring: ["org.nspasteboard.TransientType"])
        )
        #expect(decision == .rejectedPrivacyMarker)
    }

    @Test(
        "Every known reject marker is honoured",
        arguments: [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
        ]
    )
    func rejectsEveryMarker(marker: String) {
        let decision = CaptureRules().decide(snapshot(text("secret"), declaring: [marker]))
        #expect(decision == .rejectedPrivacyMarker)
    }

    @Test("Concealed content is stored but flagged")
    func flagsConcealed() throws {
        let decision = CaptureRules().decide(
            snapshot(text("hunter2"), declaring: ["org.nspasteboard.ConcealedType"])
        )
        let item = try #require(decision.item)
        #expect(item.isConcealed)
        #expect(item.previewText == "••••••••")
    }

    @Test("Excluded apps are never recorded")
    func rejectsExcludedApp() {
        let rules = CaptureRules(excludedBundleIDs: ["com.apple.keychainaccess"])
        let decision = rules.decide(snapshot(text("hello"), source: "com.apple.keychainaccess"))
        #expect(decision == .rejectedExcludedApp(bundleID: "com.apple.keychainaccess"))
    }

    @Test("An empty pasteboard produces nothing")
    func rejectsEmpty() {
        #expect(CaptureRules().decide(snapshot([:])) == .rejectedEmpty)
        #expect(CaptureRules().decide(snapshot(text("   \n  "))) == .rejectedEmpty)
    }

    @Test("Oversized payloads are dropped rather than stored")
    func rejectsTooLarge() {
        let rules = CaptureRules(maximumItemBytes: 8)
        let decision = rules.decide(snapshot(text("far too long to keep")))
        #expect(decision == .rejectedTooLarge(byteCount: 20))
    }

    @Test("Richest representation decides the kind")
    func picksRichestKind() throws {
        var representations = text("styled")
        representations[PasteboardType.rtf] = Data("{\\rtf1}".utf8)
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .richText)
        // Plain text is still kept for search and plain paste.
        #expect(item.text == "styled")
    }

    @Test("A file URL is captured as .file and labelled by filename")
    func capturesFileURL() throws {
        let url = "file:///Users/me/Pictures/shot.png"
        let representations = [PasteboardType.fileURL: Data(url.utf8)]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .file)
        #expect(item.text == "shot.png")
    }

    @Test("A file URL pointing at a folder is still captured as .file")
    func doesNotConsultTheDiskForKind() throws {
        // The rules run inside the poller's tick, which advances the change
        // count before it reads: a blocking file-system call here does not slow
        // a capture down, it loses the copies made while it blocks. So a folder
        // reads as `.file` at this stage and `ThumbnailRenderer` corrects it —
        // see `FileURLKindTests`.
        let folder = try Fixtures.makeDirectory()
        defer { try? FileManager.default.removeItem(at: folder) }

        let representations = [PasteboardType.fileURL: Data(folder.absoluteString.utf8)]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .file)
        // The trailing slash a directory URL carries is not part of the label.
        #expect(item.text == folder.lastPathComponent)
    }

    @Test("A copy of several files keeps every one of them")
    func capturesEveryFileInASelection() throws {
        // The bug: only the first pasteboard item was read, so a copy of three
        // files stored one file URL and a row that named all three — it counted
        // files it could not paste.
        let files = [
            URL(string: "file:///Users/me/Pictures/one.png"),
            URL(string: "file:///Users/me/Pictures/two.png"),
            URL(string: "file:///Users/me/Pictures/three.png"),
        ].compactMap(\.self)
        let representations = [PasteboardType.fileURL: Data(files[0].absoluteString.utf8)]

        let item = try #require(CaptureRules().decide(snapshot(representations, files: files)).item)
        #expect(item.kind == .file)
        #expect(item.fileURLs == files)
        #expect(item.text == "one.png\ntwo.png\nthree.png")
    }

    @Test("A file name comes from the file, not from the pasteboard's own text")
    func namesFilesFromTheirURLs() throws {
        // Finder writes the display names of the whole selection under
        // `public.utf8-plain-text` — extensions hidden when the user hides them,
        // and every name of a copy relayed through Universal Clipboard, which
        // hands over one file. Naming a row from that is what let one file
        // arrive wearing three names.
        let url = try #require(URL(string: "file:///Users/me/Pictures/one%20two.png"))
        let representations = [
            PasteboardType.fileURL: Data(url.absoluteString.utf8),
            PasteboardType.string: Data("one two\nthree\nfour".utf8),
        ]

        let item = try #require(CaptureRules().decide(snapshot(representations, files: [url])).item)
        #expect(item.text == "one two.png")
        #expect(item.fileURLs == [url])
    }

    @Test("A selection right at the ceiling is named in full")
    func namesEverySelectionUpToTheCeiling() throws {
        let files = selectionOf(FileSelection.maximumNamedFiles)
        let representations = [PasteboardType.fileURL: Data(files[0].absoluteString.utf8)]

        let item = try #require(CaptureRules().decide(snapshot(representations, files: files)).item)
        #expect(item.text.split(whereSeparator: \.isNewline).count == FileSelection.maximumNamedFiles)
    }

    @Test("A selection past the ceiling stops naming but keeps every file")
    func capsNamesWithoutCappingFiles() throws {
        // The text is stored, searched and re-joined on every draw, so it is
        // bounded — see ``FileSelection/maximumNamedFiles``. The files are not:
        // a row that pastes fewer files than it holds is the defect being fixed.
        let files = selectionOf(FileSelection.maximumNamedFiles + 20)
        let representations = [PasteboardType.fileURL: Data(files[0].absoluteString.utf8)]

        let item = try #require(CaptureRules().decide(snapshot(representations, files: files)).item)
        #expect(item.text.split(whereSeparator: \.isNewline).count == FileSelection.maximumNamedFiles)
        #expect(item.text.hasPrefix("file-0.txt\n"))
        #expect(item.fileURLs == files)
    }

    @Test("The payload's own file leads the list, whatever order the items came in")
    func payloadFileLeadsTheSelection() throws {
        let first = try #require(URL(string: "file:///Users/me/b.png"))
        let second = try #require(URL(string: "file:///Users/me/a.png"))
        let representations = [PasteboardType.fileURL: Data(first.absoluteString.utf8)]

        let item = try #require(
            CaptureRules().decide(snapshot(representations, files: [second, first])).item
        )
        // Paste writes the payload as item zero, so the list has to agree with
        // it about which file that is.
        #expect(item.fileURLs == [first, second])
    }

    @Test("A bare URL is captured as .link")
    func capturesLink() throws {
        let representations = [PasteboardType.url: Data("https://example.com".utf8)]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .link)
    }

    @Test("Image data needs no text to be captured")
    func capturesImageWithoutText() throws {
        let representations = [PasteboardType.png: Data([0x89, 0x50, 0x4E, 0x47])]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .image)
        #expect(item.text.isEmpty)
    }

    @Test("A declared type carrying no bytes reads as unreadable")
    func ignoresEmptyRepresentations() {
        // Was `.rejectedEmpty`. A type declared with zero bytes is exactly what
        // a denied pasteboard hands back, and an app genuinely copying an empty
        // string is vanishingly rare — so the reading that helps the user wins.
        //
        // The cost, stated plainly: `blockedThreshold` consecutive copies like
        // this with no successful read between them badge the menu bar, flip
        // the picker's empty state to "Skrepka can't read the clipboard" and
        // turn the Status pane's tick red — on a machine whose pasteboard is
        // fine. Needing a *run* of them is what keeps that trade acceptable;
        // one of these decides nothing.
        let representations = [PasteboardType.string: Data()]
        #expect(CaptureRules().decide(snapshot(representations)) == .rejectedUnreadable)
    }

    // MARK: - Blocked reads

    @Test("Declared readable types with no data read as unreadable, not empty")
    func reportsBlockedReadAsUnreadable() {
        // What a denied pasteboard looks like: the item still advertises the
        // types it holds, and every read of them comes back with nothing.
        let decision = CaptureRules().decide(
            snapshot([:], declaring: [PasteboardType.string, PasteboardType.html])
        )
        #expect(decision == .rejectedUnreadable)
    }

    @Test("A pasteboard declaring nothing Skrepka reads is empty, not blocked")
    func reportsUnknownTypesAsEmpty() {
        let decision = CaptureRules().decide(
            snapshot([:], declaring: ["com.example.private-format"])
        )
        #expect(decision == .rejectedEmpty)
    }

    @Test("Whitespace-only text is empty, not blocked")
    func reportsWhitespaceAsEmpty() {
        // The bytes arrived, so access is fine — there is just nothing worth
        // keeping. Reporting this as blocked would raise a false alarm on
        // every stray copy of a newline.
        #expect(CaptureRules().decide(snapshot(text("   \n  "))) == .rejectedEmpty)
    }

    @Test("Privacy markers still win over the unreadable check")
    func privacyMarkersTakePrecedence() {
        let decision = CaptureRules().decide(
            snapshot([:], declaring: ["org.nspasteboard.TransientType", PasteboardType.string])
        )
        #expect(decision == .rejectedPrivacyMarker)
    }
}
