import Testing

@testable import SkrepkaCore

/// The table that decides whether Skrepka is a clipboard manager or a
/// keylogger, pinned so a rename cannot quietly empty it.
///
/// Runs on both platforms even though half of what it pins is Linux-only: the
/// strings live in `SkrepkaCore` precisely so there is one answer to "may this
/// be stored", and a test that only ran where the strings were consumed would
/// leave the macOS build free to delete one.
@Suite("Privacy markers")
struct PrivacyMarkersTests {
    @Test("the nspasteboard.org markers mean do not record")
    func nspasteboardMarkers() {
        #expect(PrivacyMarkers.isRejected(types: ["org.nspasteboard.TransientType"]))
        #expect(PrivacyMarkers.isRejected(types: ["org.nspasteboard.AutoGeneratedType"]))
        #expect(PrivacyMarkers.isConcealed(types: ["org.nspasteboard.ConcealedType"]))
        // Concealed is stored and masked, not refused — the two sets are
        // deliberately different answers.
        #expect(!PrivacyMarkers.isRejected(types: ["org.nspasteboard.ConcealedType"]))
    }

    /// KDE's hint is the whole Linux privacy surface — verified 2026-09-07
    /// against `klipper/historymodel.cpp`, which compares the target's data to
    /// the literal bytes `secret` and returns *before* inserting the entry. So
    /// it belongs in `rejected` rather than `concealed`: Klipper does not store
    /// and mask a hinted clip, it never stores it.
    @Test("the KDE password-manager hint rejects rather than conceals")
    func kdeHintRejects() {
        #expect(PrivacyMarkers.isRejected(types: [PrivacyMarkers.kdePasswordManagerHint]))
        #expect(!PrivacyMarkers.isConcealed(types: [PrivacyMarkers.kdePasswordManagerHint]))
    }

    /// The one value-sensitive convention in the table. The Linux reader
    /// compares a received hint's bytes against this exact string, and Klipper
    /// stores an entry hinted anything else — `public`, most often — normally.
    /// Pinned here because the comparison lives in a target macOS never builds,
    /// so nothing else on this platform would notice it changing.
    @Test("only the literal payload counts as secret")
    func secretValueIsPinned() {
        #expect(PrivacyMarkers.kdePasswordManagerHint == "x-kde-passwordManagerHint")
        #expect(PrivacyMarkers.kdePasswordManagerHintSecret == "secret")
    }

    @Test("an ordinary type is neither rejected nor concealed")
    func ordinaryTypes() {
        #expect(!PrivacyMarkers.isRejected(types: [PasteboardType.string, PasteboardType.png]))
        #expect(!PrivacyMarkers.isConcealed(types: [PasteboardType.string, PasteboardType.png]))
    }
}
