import Foundation

/// Pasteboard types that mean "do not record this".
///
/// These are the nspasteboard.org convention, not AppKit constants — grepping
/// `NSPasteboard.h` in the macOS 26 SDK for `Concealed|Transient|AutoGenerated`
/// returns nothing. All three `org.nspasteboard.*` strings do ship inside
/// macOS 26.6.2, and password managers set them, so honouring them is the
/// difference between a clipboard manager and a keylogger.
///
/// One table for both platforms rather than a Linux one beside it: the whole
/// point of the type is that there is exactly one answer to "may this be
/// stored", and two tables is how one of them ends up missing a marker.
package enum PrivacyMarkers {
    /// The one Linux convention there is.
    ///
    /// Verified 2026-09-07 against `klipper/historymodel.cpp` in
    /// plasma-workspace, which compares the target's data to the literal bytes
    /// `secret` and returns *before* inserting the entry — so it means reject
    /// outright, not store-and-mask. KeePassXC (`src/gui/Clipboard.cpp`),
    /// plasma-pass, QtPass, pwsafe and `wl-copy --sensitive` all set it, and
    /// Klipper, CopyQ, kdeconnect, fcitx5 and clipcat all honour it.
    ///
    /// There is no GNOME or GTK equivalent — verified by searching GPaste,
    /// which has no MIME-based sensitivity at all. `CLIPBOARD_STATE=sensitive`
    /// is an environment variable `wl-paste --watch` sets for its child, and
    /// `wl-clipboard`'s own manual says it sets it only on seeing this same
    /// KDE target. So this string is the whole Linux privacy surface.
    ///
    /// **Value-sensitive, unlike every other entry here.** Only the payload
    /// `secret` counts; Klipper stores an entry hinted `public` normally. A set
    /// of type names cannot express that, so the Linux reader resolves the
    /// value and declares this type only when it resolved to a rejection — see
    /// `LinuxRepresentationMap` in `SkrepkaLinuxPlatform`.
    package static let kdePasswordManagerHint = "x-kde-passwordManagerHint"

    /// The payload that makes ``kdePasswordManagerHint`` mean "do not store".
    package static let kdePasswordManagerHintSecret = "secret"

    /// Content that must never be stored at all.
    static let rejected: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        kdePasswordManagerHint,
    ]

    /// Content that may be stored but must be masked in the UI.
    static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.agilebits.onepassword",
    ]

    /// True when any representation marks the content as not-for-recording.
    static func isRejected(types: some Sequence<String>) -> Bool {
        types.contains { rejected.contains($0) }
    }

    /// True when any representation marks the content as sensitive.
    static func isConcealed(types: some Sequence<String>) -> Bool {
        types.contains { concealed.contains($0) }
    }
}
