import Foundation
import Testing

@testable import ClippyCore

@Suite("Capture rules")
struct CaptureRulesTests {
    private func snapshot(
        _ representations: [String: Data],
        declaring extraTypes: [String] = [],
        source: String? = nil
    ) -> PasteboardSnapshot {
        PasteboardSnapshot(
            representations: representations,
            declaredTypes: Array(representations.keys) + extraTypes,
            sourceBundleID: source
        )
    }

    private func text(_ string: String) -> [String: Data] {
        [PasteboardType.string: Data(string.utf8)]
    }

    @Test("Plain text is captured as .text")
    func capturesPlainText() throws {
        let decision = CaptureRules().decide(snapshot(text("hello")))
        let item = try #require(decision.item)
        #expect(item.kind == .text)
        #expect(item.text == "hello")
        #expect(!item.isConcealed)
    }

    @Test("Transient markers are rejected before any data is read")
    func rejectsTransientMarker() {
        let decision = CaptureRules().decide(
            snapshot(text("secret"), declaring: ["org.nspasteboard.TransientType"])
        )
        #expect(decision == .rejectedPrivacyMarker)
    }

    @Test(
        "Every known reject marker is honoured",
        arguments: [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
        ]
    )
    func rejectsEveryMarker(marker: String) {
        let decision = CaptureRules().decide(snapshot(text("secret"), declaring: [marker]))
        #expect(decision == .rejectedPrivacyMarker)
    }

    @Test("Concealed content is stored but flagged")
    func flagsConcealed() throws {
        let decision = CaptureRules().decide(
            snapshot(text("hunter2"), declaring: ["org.nspasteboard.ConcealedType"])
        )
        let item = try #require(decision.item)
        #expect(item.isConcealed)
        #expect(item.previewText == "••••••••")
    }

    @Test("Excluded apps are never recorded")
    func rejectsExcludedApp() {
        let rules = CaptureRules(excludedBundleIDs: ["com.apple.keychainaccess"])
        let decision = rules.decide(snapshot(text("hello"), source: "com.apple.keychainaccess"))
        #expect(decision == .rejectedExcludedApp(bundleID: "com.apple.keychainaccess"))
    }

    @Test("An empty pasteboard produces nothing")
    func rejectsEmpty() {
        #expect(CaptureRules().decide(snapshot([:])) == .rejectedEmpty)
        #expect(CaptureRules().decide(snapshot(text("   \n  "))) == .rejectedEmpty)
    }

    @Test("Oversized payloads are dropped rather than stored")
    func rejectsTooLarge() {
        let rules = CaptureRules(maximumItemBytes: 8)
        let decision = rules.decide(snapshot(text("far too long to keep")))
        #expect(decision == .rejectedTooLarge(byteCount: 20))
    }

    @Test("Richest representation decides the kind")
    func picksRichestKind() throws {
        var representations = text("styled")
        representations[PasteboardType.rtf] = Data("{\\rtf1}".utf8)
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .richText)
        // Plain text is still kept for search and plain paste.
        #expect(item.text == "styled")
    }

    @Test("A file URL is captured as .file and labelled by filename")
    func capturesFileURL() throws {
        let url = "file:///Users/me/Pictures/shot.png"
        let representations = [PasteboardType.fileURL: Data(url.utf8)]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .file)
        #expect(item.text == "shot.png")
    }

    @Test("A bare URL is captured as .link")
    func capturesLink() throws {
        let representations = [PasteboardType.url: Data("https://example.com".utf8)]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .link)
    }

    @Test("Image data needs no text to be captured")
    func capturesImageWithoutText() throws {
        let representations = [PasteboardType.png: Data([0x89, 0x50, 0x4E, 0x47])]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .image)
        #expect(item.text.isEmpty)
    }

    @Test("Empty representations are discarded, markers still respected")
    func ignoresEmptyRepresentations() {
        let representations = [PasteboardType.string: Data()]
        #expect(CaptureRules().decide(snapshot(representations)) == .rejectedEmpty)
    }
}
