import Foundation
import Testing

@testable import ClippyCore

@Suite("Capture rules")
struct CaptureRulesTests {
    private func snapshot(
        _ representations: [String: Data],
        declaring extraTypes: [String] = [],
        source: String? = nil
    ) -> PasteboardSnapshot {
        PasteboardSnapshot(
            representations: representations,
            declaredTypes: Array(representations.keys) + extraTypes,
            sourceBundleID: source
        )
    }

    private func text(_ string: String) -> [String: Data] {
        [PasteboardType.string: Data(string.utf8)]
    }

    @Test("Plain text is captured as .text")
    func capturesPlainText() throws {
        let decision = CaptureRules().decide(snapshot(text("hello")))
        let item = try #require(decision.item)
        #expect(item.kind == .text)
        #expect(item.text == "hello")
        #expect(!item.isConcealed)
    }

    @Test("Transient markers are rejected before any data is read")
    func rejectsTransientMarker() {
        let decision = CaptureRules().decide(
            snapshot(text("secret"), declaring: ["org.nspasteboard.TransientType"])
        )
        #expect(decision == .rejectedPrivacyMarker)
    }

    @Test(
        "Every known reject marker is honoured",
        arguments: [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
        ]
    )
    func rejectsEveryMarker(marker: String) {
        let decision = CaptureRules().decide(snapshot(text("secret"), declaring: [marker]))
        #expect(decision == .rejectedPrivacyMarker)
    }

    @Test("Concealed content is stored but flagged")
    func flagsConcealed() throws {
        let decision = CaptureRules().decide(
            snapshot(text("hunter2"), declaring: ["org.nspasteboard.ConcealedType"])
        )
        let item = try #require(decision.item)
        #expect(item.isConcealed)
        #expect(item.previewText == "••••••••")
    }

    @Test("Excluded apps are never recorded")
    func rejectsExcludedApp() {
        let rules = CaptureRules(excludedBundleIDs: ["com.apple.keychainaccess"])
        let decision = rules.decide(snapshot(text("hello"), source: "com.apple.keychainaccess"))
        #expect(decision == .rejectedExcludedApp(bundleID: "com.apple.keychainaccess"))
    }

    @Test("An empty pasteboard produces nothing")
    func rejectsEmpty() {
        #expect(CaptureRules().decide(snapshot([:])) == .rejectedEmpty)
        #expect(CaptureRules().decide(snapshot(text("   \n  "))) == .rejectedEmpty)
    }

    @Test("Oversized payloads are dropped rather than stored")
    func rejectsTooLarge() {
        let rules = CaptureRules(maximumItemBytes: 8)
        let decision = rules.decide(snapshot(text("far too long to keep")))
        #expect(decision == .rejectedTooLarge(byteCount: 20))
    }

    @Test("Richest representation decides the kind")
    func picksRichestKind() throws {
        var representations = text("styled")
        representations[PasteboardType.rtf] = Data("{\\rtf1}".utf8)
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .richText)
        // Plain text is still kept for search and plain paste.
        #expect(item.text == "styled")
    }

    @Test("A file URL is captured as .file and labelled by filename")
    func capturesFileURL() throws {
        let url = "file:///Users/me/Pictures/shot.png"
        let representations = [PasteboardType.fileURL: Data(url.utf8)]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .file)
        #expect(item.text == "shot.png")
    }

    @Test("A bare URL is captured as .link")
    func capturesLink() throws {
        let representations = [PasteboardType.url: Data("https://example.com".utf8)]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .link)
    }

    @Test("Image data needs no text to be captured")
    func capturesImageWithoutText() throws {
        let representations = [PasteboardType.png: Data([0x89, 0x50, 0x4E, 0x47])]
        let item = try #require(CaptureRules().decide(snapshot(representations)).item)
        #expect(item.kind == .image)
        #expect(item.text.isEmpty)
    }

    @Test("A declared type carrying no bytes reads as unreadable")
    func ignoresEmptyRepresentations() {
        // Was `.rejectedEmpty`. A type declared with zero bytes is exactly what
        // a denied pasteboard hands back, and an app genuinely copying an empty
        // string is vanishingly rare — so the reading that helps the user wins.
        //
        // The cost, stated plainly: `blockedThreshold` consecutive copies like
        // this with no successful read between them badge the menu bar, flip
        // the picker's empty state to "Clippy can't read the clipboard" and
        // turn the Status pane's tick red — on a machine whose pasteboard is
        // fine. Needing a *run* of them is what keeps that trade acceptable;
        // one of these decides nothing.
        let representations = [PasteboardType.string: Data()]
        #expect(CaptureRules().decide(snapshot(representations)) == .rejectedUnreadable)
    }

    // MARK: - Blocked reads

    @Test("Declared readable types with no data read as unreadable, not empty")
    func reportsBlockedReadAsUnreadable() {
        // What a denied pasteboard looks like: the item still advertises the
        // types it holds, and every read of them comes back with nothing.
        let decision = CaptureRules().decide(
            snapshot([:], declaring: [PasteboardType.string, PasteboardType.html])
        )
        #expect(decision == .rejectedUnreadable)
    }

    @Test("A pasteboard declaring nothing Clippy reads is empty, not blocked")
    func reportsUnknownTypesAsEmpty() {
        let decision = CaptureRules().decide(
            snapshot([:], declaring: ["com.example.private-format"])
        )
        #expect(decision == .rejectedEmpty)
    }

    @Test("Whitespace-only text is empty, not blocked")
    func reportsWhitespaceAsEmpty() {
        // The bytes arrived, so access is fine — there is just nothing worth
        // keeping. Reporting this as blocked would raise a false alarm on
        // every stray copy of a newline.
        #expect(CaptureRules().decide(snapshot(text("   \n  "))) == .rejectedEmpty)
    }

    @Test("Privacy markers still win over the unreadable check")
    func privacyMarkersTakePrecedence() {
        let decision = CaptureRules().decide(
            snapshot([:], declaring: ["org.nspasteboard.TransientType", PasteboardType.string])
        )
        #expect(decision == .rejectedPrivacyMarker)
    }
}
